#!/bin/bash

killall rviz
#SEQUENCE="2019-01-16-11-53-11-radar-oxford-10k" #
SEQUENCE="2019-01-10-12-32-52-radar-oxford-10k"
current_date=`date '+%Y-%m-%d_%H:%M'`
EVALUATION_description="cfear-1"
BAG_BASE_PATH="/${BAG_LOCATION}/oxford-eval-sequences" #Change this to the directory where you have the bag files
BAG_FILE_PATH="${BAG_BASE_PATH}/${SEQUENCE}/radar/${SEQUENCE}.bag"
echo "${BAG_FILE_PATH}"
EVAL_BASE_DIR="${BAG_BASE_PATH}/eval/${current_date}"
est_dir="${EVAL_BASE_DIR}/est/"
gt_dir="${EVAL_BASE_DIR}/gt/"
mkdir -p "${est_dir}"
mkdir -p "${gt_dir}"




##### PARAMETERS
export radar_ccw="false"
export soft_constraint="false"
export disable_compensate="false"
export cost_type="P2P"
export submap_scan_size="4"
export registered_min_keyframe_dist="1.5"
export res="3"

export REGULARIZATION="0" #not relevant
export COVAR_SCALE="500" #not relevant

export LOSS_TYPE="Huber"
export LOSS_LIMIT="0.1"
export range_res="0.0438"
export weight_intensity="true"

export filter_type="kstrong"
export zmin="60.0" # false alarm rate For CA-CFAR, this is , a small positive value e.g. 0.01
export kstrong="40"

#export filter_type="CA-CFAR"
#export zmin="20.0"
#export kstrong="10"           # NB_GUARD_CELLS For CA-CFAR
#export COVAR_SCALE="500"      # Window size For CA-CFAR
#export REGULARIZATION="0.0001" #False alarm rate # [0.01 0.001 0.0001]]



pars="--range-res ${range_res} --sequence ${SEQUENCE} --radar_ccw ${radar_ccw} --soft_constraint ${soft_constraint} --disable_compensate ${disable_compensate} --cost_type ${cost_type} --submap_scan_size ${submap_scan_size} --registered_min_keyframe_dist ${registered_min_keyframe_dist} --res ${res} --k_strongest ${kstrong} --bag_path ${BAG_FILE_PATH} --est_directory ${est_dir} --gt_directory ${gt_dir} --job_nr 1 --z-min ${zmin} --loss_type ${LOSS_TYPE} --loss_limit ${LOSS_LIMIT} --regularization ${REGULARIZATION} --covar_scale ${COVAR_SCALE} --weight_intensity ${weight_intensity} --filter-type ${filter_type} --method ${EVALUATION_description} --weight_option 4"
echo "|||||Estimating odometry with parameters: ${pars}||||"
roslaunch cfear_radarodometry vis.launch&
rosrun cfear_radarodometry offline_odometry ${pars} #>/dev/null
