#!/bin/bash

killall rviz

SEQUENCE="Volvo_CE"
current_date=`date '+%Y-%m-%d_%H:%M'`
EVALUATION_description="cfear-x"

BAG_BASE_PATH="/${BAG_LOCATION}/Volvo_CE" #Change this to the directory where you have the bag files
BAG_FILE_PATH="${BAG_BASE_PATH}/${SEQUENCE}.bag"
echo "${BAG_FILE_PATH}"
EVAL_BASE_DIR="${BAG_BASE_PATH}/eval/${current_date}"
est_dir="${EVAL_BASE_DIR}/est/"
gt_dir="${EVAL_BASE_DIR}/gt/"
mkdir -p "${est_dir}"
mkdir -p "${gt_dir}"





#PARAMETERS CFEAR-3
#export cost_type="P2P"
#export submap_scan_size="4"
#export registered_min_keyframe_dist="1.5"
#export res="3"
#export kstrong="40"
#export zmin="60"
#export weight_option="4"
#export weight_intensity="true"


#PARAMETERS CFEAR-3
#export cost_type="P2P"
#export submap_scan_size="4"
#export registered_min_keyframe_dist="1.5"
#export res="3"
#export kstrong="40"
#export zmin="60"
#export weight_option="4"
#export weight_intensity="true"

# CFEAR-2
export cost_type="P2L"
export submap_scan_size="3"
export registered_min_keyframe_dist="1.5"
export res="3.5"
export kstrong="12"
export zmin="70"
export weight_option="4"
export weight_intensity="true"

# CFEAR-1
#export cost_type="P2L"
#export submap_scan_size="1"
#export registered_min_keyframe_dist="1.5"
#export res="3.5"
#export kstrong="12"
#export zmin="70"
#export weight_option="4"
#export weight_intensity="true"

# OTHER PARAMETERS #
export range_res="0.175238"
export radar_ccw="true" #False for oxford, otherwise true
export soft_constraint="false"
export disable_compensate="false"
export dataset="Volvo-CE"
export LOSS_TYPE="Huber"
export LOSS_LIMIT="0.1"


pars="--range-res ${range_res} --sequence ${SEQUENCE} --radar_ccw ${radar_ccw} --soft_constraint ${soft_constraint} --disable_compensate ${disable_compensate} --cost_type ${cost_type} --submap_scan_size ${submap_scan_size} --registered_min_keyframe_dist ${registered_min_keyframe_dist} --res ${res} --k_strongest ${kstrong} --bag_path ${BAG_FILE_PATH} --est_directory ${est_dir} --gt_directory ${gt_dir} --job_nr 1 --z-min ${zmin} --loss_type ${LOSS_TYPE} --loss_limit ${LOSS_LIMIT}  --weight_intensity ${weight_intensity} --method ${EVALUATION_description} --weight_option ${weight_option} --dataset ${dataset}"
echo "|||||Estimating odometry with parameters: ${pars}||||"
roslaunch cfear_radarodometry vis.launch&
rosrun cfear_radarodometry offline_odometry ${pars} #>/dev/null
