#!/bin/bash

killall rviz
#SEQUENCE="2019-01-16-11-53-11-radar-oxford-10k"
#SEQUENCE="DCC01"
SEQUENCE="2020-09-18-14-38-03"
current_date=`date '+%Y-%m-%d_%H:%M'`
EVAL_BASE_DIR="/home/daniel/rosbag/kvarntorp/trash_eval/${current_date}"
JOB_NR=${11}
source pars >/dev/null
#echo "execute: seq:${SEQUENCE}, base: ${EVAL_BASE_DIR}"
est_dir="${EVAL_BASE_DIR}/est/"
gt_dir="${EVAL_BASE_DIR}/gt/"
mkdir -p "${est_dir}"
mkdir -p "${gt_dir}"
BAG_BASE_PATH="/home/daniel/rosbag/kvarntorp"
BAG_FILE_PATH="${BAG_BASE_PATH}/${SEQUENCE}.bag"
echo "${BAG_FILE_PATH}"


export range_resolution="0.175"

#CFEAR-2
export radar_ccw="false"
export soft_constraint="false"
export disable_compensate="false"
export cost_type="P2L"
export submap_scan_size="3"
export registered_min_keyframe_dist="1.5"
export res="3.5"
export kstrong="12"
export zmin="65"
export SAVE_PCD="" #--savepcd
export dataset="kvarntorp"

#CFEAR-1
#export radar_ccw="true"
#export soft_constraint="false"
#export disable_compensate="false"
#export cost_type="P2L"
#export submap_scan_size="1"
#export registered_min_keyframe_dist="1.5"
#export res="3"
#export kstrong="15"
#export zmin="65"


#CFEAR-3
#SEQUENCE="2019-01-17-13-26-39-radar-oxford-10k"
#export radar_ccw="false"
#export soft_constraint="false"
#export disable_compensate="false"
#export cost_type="P2P"
#export submap_scan_size="4"
#export registered_min_keyframe_dist="1.5"
#export res="3"
#export kstrong="40"
#export zmin="40"

#export radar_ccw="false"
#export soft_constraint="false"
#export disable_compensate="false"
#export cost_type="P2L"
#export submap_scan_size="1"
#export registered_min_keyframe_dist="1.5"
#export res="3.5"
#export kstrong="12"
#export zmin="40"




pars="--range-res ${range_resolution} --sequence ${SEQUENCE} --radar_ccw ${radar_ccw} --soft_constraint ${soft_constraint} --disable_compensate ${disable_compensate} --cost_type ${cost_type} --submap_scan_size ${submap_scan_size} --registered_min_keyframe_dist ${registered_min_keyframe_dist} --res ${res} --k_strongest ${kstrong} --bag_path ${BAG_FILE_PATH} --est_directory ${est_dir} --gt_directory ${gt_dir} --job_nr 1 --z-min ${zmin} --dataset ${dataset} --savepcd"
echo "|||||Estimating odometry with parameters: ${pars}||||"

roslaunch cfear_radarodometry vis.launch&
rosrun cfear_radarodometry offline_odometry ${pars} #>/dev/null
