#!/bin/bash
###################### USAGE ##########################
# (1) Create folder ros rosbag
# mkdir -p /home/${USER}/Documents/oxford-eval-sequences/2019-01-10-12-32-52-radar-oxford-10k
# cd /home/${USER}/Documents/oxford-eval-sequences/2019-01-10-12-32-52-radar-oxford-10k
# download rosbag from https://drive.google.com/drive/folders/12YNIvHQqSO5Et3UIzKD1z3XQACpoGZ1L to the created directory
#
# NOTE!!! The estimated odometry is mirrored as the sensor is turned upside-down
killall rviz

SEQUENCE="2019-01-10-12-32-52-radar-oxford-10k"
current_date=`date '+%Y-%m-%d_%H:%M'`
EVALUATION_description="cfear-x"

#For 2019-01-16-11-53-11-radar-oxford-10k
#BAG_BASE_PATH="/home/${USER}/Documents/oxford-eval-sequences/2019-01-16-11-53-11-radar-oxford-10k/" #Must be set, will contain the output of the odometry
#BAG_FILE_PATH="${BAG_BASE_PATH}/2019-01-16-11-53-11-radar-oxford-10k.bag" #can changed to any location

#For2019-01-10-12-32-52-radar-oxford-10k
BAG_BASE_PATH="/home/${USER}/Documents/oxford-eval-sequences/2019-01-10-12-32-52-radar-oxford-10k/" #Must be set, will contain the output of the odometry
BAG_FILE_PATH="${BAG_BASE_PATH}/2019-01-10-12-32-52-radar-oxford-10k.bag" #can changed to any location

echo "Bag file: ${BAG_FILE_PATH}"
EVAL_BASE_DIR="${BAG_BASE_PATH}/eval/${current_date}"
est_dir="${EVAL_BASE_DIR}/est/"
gt_dir="${EVAL_BASE_DIR}/gt/"
mkdir -p "${est_dir}"
mkdir -p "${gt_dir}"



# PARAMETERS CFEAR-3
export cost_type="P2P"
export submap_scan_size="4"
export registered_min_keyframe_dist="1.5"
export res="3"
export kstrong="40"
export zmin="60"
export weight_option="4"
export weight_intensity="true"

# PARAMETERS CFEAR-2
#export cost_type="P2L"
#export submap_scan_size="3"
#export registered_min_keyframe_dist="1.5"
#export res="3"
#export kstrong="15"
#export zmin="70"
#export weight_intensity="true"


# PARAMETERS CFEAR-1
#export cost_type="P2L"
#export submap_scan_size="2"
#export registered_min_keyframe_dist="0" # CHANGE THIS to 1.5!!!!!!!!!!!
#export res="3"
#export kstrong="12"
#export zmin="70"
#export weight_option="4"
#export weight_intensity="true"

# OTHER PARAMETERS #
export range_res="0.0438"
export radar_ccw="false" #False for oxford, otherwise true
export soft_constraint="false"
export disable_compensate="false"
export dataset="oxford"
export LOSS_TYPE="Huber"
export LOSS_LIMIT="0.1"


pars="--range-res ${range_res} --sequence ${SEQUENCE} --radar_ccw ${radar_ccw} --soft_constraint ${soft_constraint} --disable_compensate ${disable_compensate} --cost_type ${cost_type} --submap_scan_size ${submap_scan_size} --registered_min_keyframe_dist ${registered_min_keyframe_dist} --res ${res} --k_strongest ${kstrong} --bag_path ${BAG_FILE_PATH} --est_directory ${est_dir} --gt_directory ${gt_dir} --job_nr 1 --z-min ${zmin} --loss_type ${LOSS_TYPE} --loss_limit ${LOSS_LIMIT}  --weight_intensity ${weight_intensity} --method ${EVALUATION_description} --weight_option ${weight_option} --dataset ${dataset}"
echo "|||||Estimating odometry with parameters: ${pars}||||"
roslaunch cfear_radarodometry vis.launch&
rosrun cfear_radarodometry offline_odometry ${pars} #>/dev/null
